version: "3.9"

services:
  proxy:
    image: nginx:1.25 # this will use the latest version of 1.23
    ports:
      - "80:80" # expose 80 on host and sent to 80 in container
    # mount bind to nginx.conf file with containes all the proxy configs
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # :ro stands for read only
  web:
    image: httpd:2 # this will use the latest apache v2
    # any html inside public-html file will be served through nginx proxy
    volumes:
      - ./public-html/:/usr/local/apache2/htdocs/
