version: "3.9"

services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - frontend_network
    depends_on:
      - redis
    deploy:
      replicas: 10

  redis:
    image: redis:3.2
    networks:
      - frontend_network
    deploy:
      replicas: 1

  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend_network
      - backend_networks
    depends_on:
      - db
      - redis
    deploy:
      replicas: 2

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend_networks
    depends_on:
      - redis
    deploy:
      replicas: 1

  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend_networks
    depends_on:
      - db
    deploy:
      replicas: 1

  visualizer:
    image: bretfisher/visualizer
    ports:
      - 8080:8080
    stop_grace_period: 1m30s
    networks:
      - frontend_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  frontend_network:
  backend_networks:

volumes:
  db-data:
