version: "3.9"

services:
  mariadb:
    image: mariadb
    secrets:
      - mariadb_root_password
      - mariadb_user
      - mariadb_user_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_USER_FILE: /run/secrets/mariadb_user
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_DATABASE: drupalDB

# docker secrests already being created before hand, in that case we have to use external: true
secrets:
  mariadb_root_password:
    external: true
  mariadb_user:
    external: true
  mariadb_user_password:
    external: true
