version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpressDB
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpressdb

  wordpressdb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: wordpressDB
    volumes:
      - ./wordpressdb:/var/lib/mysql
