version: "3.9"

services:
  drupal:
    image: drupal
    ports:
      - "80:80"
    volumes:
      - drupal-sites:/var/www/html/sites
    depends_on:
      - drupaldb
    networks:
      - drupal_network
    deploy:
      replicas: 3

  drupaldb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: bisso
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: drupalDB
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - drupal_network
    deploy:
      replicas: 1

volumes:
  db-data:
  drupal-sites:
networks:
  drupal_network:
