version: "3.9"

services:
  mariadb:
    image: mariadb
    secrets:
      - mariadb_root_password
      - mariadb_user
      - mariadb_user_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MARIADB_USER_FILE: /run/secrets/mariadb_user
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_user_password
      MARIADB_DATABASE: drupalDB

secrets:
  mariadb_root_password:
    # when docker secret file is not being created and need to be created based on value of txt file
    file: ./mariadb_root_password.txt
  mariadb_user:
    file: ./mariadb_user.txt
  mariadb_user_password:
    file: ./mariadb_user_password.txt
