version: "3.9"

services:
  drupal:
    image: bishwajitkuat/drupal-custom:test2
    ports:
      - "80:80"
    volumes:
      - drupal-sites:/var/www/html/sites
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
    depends_on:
      - drupaldb
    restart: always

  drupaldb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: bisso
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: drupalDB
    volumes:
      - ./drupaldb:/var/lib/mysql
    restart: always
volumes:
  drupal-sites:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
